name: tosonow
version: ${project.version}
main: ga.ganma.minigames.TosoNow
author: ganma
commands:
  toso:
    description: tosogame command.
    permission: tosonow.command.toso
  phone:
    description: phone command.
permissions:
  tosonow.command.toso:
    default: op
